version: '2'
services:
  ui:
    build: ./salesloft-frontend
    ports:
      - '8081:80'
    depends_on:
      - api
  api:
    build: ./salesloft-backend
    ports:
      - '4000:4000'
    environment:
      - API_KEY